server:
  port: 21211
spring:
  profiles:
    active: dev
---
spring:
  profile: dev
  rabbitmq:
    host: localhost
    port: 5672 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/
    registerWithEureka: false
    fetchRegistry: false
  instance:
    lease-renewal-interval-in-seconds: 5
management:
  security:
    enabled: false
debug: true
logging:
  file: eureka.log
