server:
  port: 21240

spring:
  application:
    name: kstream-service
  rabbitmq:
    host: localhost
    port: 5672 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:21211/eureka/
    registry-fetch-interval-seconds: 3
management:
  security:
    enabled: false
debug: true
logging:
  file: kstream.log
