server:
  port: 21220
  
spring:
  profiles:
    active: dev
    
---

spring:
  profile: dev
  application:
    name: mybatis-service
  rabbitmq:
    host: localhost
    port: 5672 
  datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/mybatis
        username: root
        password: root
    
mybatis: 
  mapperLocations: mapper/*.xml
  typeAliasesPackage: com.lc.model
  config: mybatis-config.xml
  checkConfigLocation: true
  executorType: SIMPLE

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:21211/eureka/
    registry-fetch-interval-seconds: 3
    
management:
  security:
    enabled: false
    
debug: true

logging:
  file: mybatis.log
