server:
  port: 21250

spring:
  application:
    name: rabbitmq-service
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:21211/eureka/
    registry-fetch-interval-seconds: 3

test:
  name: li
