server:
  port: 21250
  
spring:
  profiles:
    active: dev
    
--- 

spring:
  profile: dev
  application:
    name: rabbitmq-service
  rabbitmq:
    host: localhost
    port: 5672 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:21211/eureka/
    registry-fetch-interval-seconds: 3
    
test:
  name: 李儒志
  
management:
  security:
    enabled: false
    
debug: true

logging:
  file: rabbitmq.log
