server:
  port: 21250

spring:
  application:
    name: rabbitmq-service
  rabbitmq:
    host: localhost
    port: 5672 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:21211/eureka/
    registry-fetch-interval-seconds: 3
test:
  name: 张小红
management:
  security:
    enabled: false
