server:
  port: 21220
spring:
  profiles:
    active: dev
---
spring:
  profile: dev
  application:
    name: redis-service
  redis:
    host: localhost
    port: 6379
    pool:
      max-idle: 8
      min-idle: 0
      max-active: 8
      max-wait: 5
  rabbitmq:
    host: localhost
    port: 5672 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:21211/eureka/
    registry-fetch-interval-seconds: 3
    
management:
  security:
    enabled: false
debug: true
logging:
  file: redis.log
