server:
  port: 21230

spring:
  application:
    name: ribbon-server
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:21211/eureka/
    registry-fetch-interval-seconds: 3

redis:
  server: http://redis-server
