server:
  port: 21230

spring:
  application:
    name: ribbon-service
  rabbitmq:
    host: localhost
    port: 5672 
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:21211/eureka/
    registry-fetch-interval-seconds: 3

redis:
  server: 
    url: http://redis-service
    
management:
  security:
    enabled: false
